# Conda environment
name: hls-vis-gpp

channels:
  - conda-forge
  - defaults
  - anaconda
  - rapidsai
  - nvidia

dependencies:
  - rioxarray
  - cupy
  - cudatoolkit=11.2
  - dask-cuda
  - cudnn
  - cutensor
  - nccl
  # - rapids-blazing=21.06
  # - cudatoolkit=11.2
  - ipykernel
  - ipywidgets
  - matplotlib
  - geopandas
